.TH "/home/shangwei/catkin_ws/src/metal1/mcu_control/ros_lib/posedetection_msgs Directory Reference" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/shangwei/catkin_ws/src/metal1/mcu_control/ros_lib/posedetection_msgs Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCurve1D\&.h\fP"
.br
.ti -1c
.RI "file \fBDetect\&.h\fP"
.br
.ti -1c
.RI "file \fBFeature0D\&.h\fP"
.br
.ti -1c
.RI "file \fBFeature0DDetect\&.h\fP"
.br
.ti -1c
.RI "file \fBFeature1D\&.h\fP"
.br
.ti -1c
.RI "file \fBFeature1DDetect\&.h\fP"
.br
.ti -1c
.RI "file \fBImageFeature0D\&.h\fP"
.br
.ti -1c
.RI "file \fBImageFeature1D\&.h\fP"
.br
.ti -1c
.RI "file \fBObject6DPose\&.h\fP"
.br
.ti -1c
.RI "file \fBObjectDetection\&.h\fP"
.br
.ti -1c
.RI "file \fBTargetObj\&.h\fP"
.br
.in -1c
