.TH "/home/shangwei/catkin_ws/src/metal1/mcu_control/ros_lib/app_manager Directory Reference" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/shangwei/catkin_ws/src/metal1/mcu_control/ros_lib/app_manager Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBApp\&.h\fP"
.br
.ti -1c
.RI "file \fBAppInstallationState\&.h\fP"
.br
.ti -1c
.RI "file \fBAppList\&.h\fP"
.br
.ti -1c
.RI "file \fBAppStatus\&.h\fP"
.br
.ti -1c
.RI "file \fBClientApp\&.h\fP"
.br
.ti -1c
.RI "file \fBExchangeApp\&.h\fP"
.br
.ti -1c
.RI "file \fBGetAppDetails\&.h\fP"
.br
.ti -1c
.RI "file \fBGetInstallationState\&.h\fP"
.br
.ti -1c
.RI "file \fBIcon\&.h\fP"
.br
.ti -1c
.RI "file \fBInstallApp\&.h\fP"
.br
.ti -1c
.RI "file \fBKeyValue\&.h\fP"
.br
.ti -1c
.RI "file \fBListApps\&.h\fP"
.br
.ti -1c
.RI "file \fBStartApp\&.h\fP"
.br
.ti -1c
.RI "file \fBStatusCodes\&.h\fP"
.br
.ti -1c
.RI "file \fBStopApp\&.h\fP"
.br
.ti -1c
.RI "file \fBUninstallApp\&.h\fP"
.br
.in -1c
