.TH "actionlib::TestRequestGoal" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
actionlib::TestRequestGoal \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBTERMINATE_SUCCESS\fP = 0 }"
.br
.ti -1c
.RI "enum { \fBTERMINATE_ABORTED\fP = 1 }"
.br
.ti -1c
.RI "enum { \fBTERMINATE_REJECTED\fP = 2 }"
.br
.ti -1c
.RI "enum { \fBTERMINATE_LOSE\fP = 3 }"
.br
.ti -1c
.RI "enum { \fBTERMINATE_DROP\fP = 4 }"
.br
.ti -1c
.RI "enum { \fBTERMINATE_EXCEPTION\fP = 5 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int32_t \fBterminate_status\fP"
.br
.ti -1c
.RI "bool \fBignore_cancel\fP"
.br
.ti -1c
.RI "const char * \fBresult_text\fP"
.br
.ti -1c
.RI "int32_t \fBthe_result\fP"
.br
.ti -1c
.RI "bool \fBis_simple_client\fP"
.br
.ti -1c
.RI "\fBros::Duration\fP \fBdelay_accept\fP"
.br
.ti -1c
.RI "\fBros::Duration\fP \fBdelay_terminate\fP"
.br
.ti -1c
.RI "\fBros::Duration\fP \fBpause_status\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
