.TH "actionlib_msgs::GoalStatus" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
actionlib_msgs::GoalStatus \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBPENDING\fP = 0 }"
.br
.ti -1c
.RI "enum { \fBACTIVE\fP = 1 }"
.br
.ti -1c
.RI "enum { \fBPREEMPTED\fP = 2 }"
.br
.ti -1c
.RI "enum { \fBSUCCEEDED\fP = 3 }"
.br
.ti -1c
.RI "enum { \fBABORTED\fP = 4 }"
.br
.ti -1c
.RI "enum { \fBREJECTED\fP = 5 }"
.br
.ti -1c
.RI "enum { \fBPREEMPTING\fP = 6 }"
.br
.ti -1c
.RI "enum { \fBRECALLING\fP = 7 }"
.br
.ti -1c
.RI "enum { \fBRECALLED\fP = 8 }"
.br
.ti -1c
.RI "enum { \fBLOST\fP = 9 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBactionlib_msgs::GoalID\fP \fBgoal_id\fP"
.br
.ti -1c
.RI "uint8_t \fBstatus\fP"
.br
.ti -1c
.RI "const char * \fBtext\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
