.TH "andbot::DeviceCheckResponse" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
andbot::DeviceCheckResponse \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBid1\fP"
.br
.ti -1c
.RI "bool \fBid2\fP"
.br
.ti -1c
.RI "bool \fBid3\fP"
.br
.ti -1c
.RI "bool \fBid4\fP"
.br
.ti -1c
.RI "bool \fBid5\fP"
.br
.ti -1c
.RI "bool \fBid6\fP"
.br
.ti -1c
.RI "bool \fBid7\fP"
.br
.ti -1c
.RI "bool \fBid8\fP"
.br
.ti -1c
.RI "bool \fBid9\fP"
.br
.ti -1c
.RI "bool \fBid10\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
