.TH "ArduinoHardware" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ArduinoHardware \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArduinoHardware\fP (SERIAL_CLASS *io, long baud=57600)"
.br
.ti -1c
.RI "\fBArduinoHardware\fP (\fBArduinoHardware\fP &h)"
.br
.ti -1c
.RI "void \fBsetBaud\fP (long baud)"
.br
.ti -1c
.RI "int \fBgetBaud\fP ()"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "int \fBread\fP ()"
.br
.ti -1c
.RI "void \fBwrite\fP (uint8_t *data, int length)"
.br
.ti -1c
.RI "unsigned long \fBtime\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "SERIAL_CLASS * \fBiostream\fP"
.br
.ti -1c
.RI "long \fBbaud_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
