.TH "calibration_msgs::LaserMeasurement" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
calibration_msgs::LaserMeasurement \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd_msgs::Header\fP \fBheader\fP"
.br
.ti -1c
.RI "const char * \fBlaser_id\fP"
.br
.ti -1c
.RI "uint8_t \fBjoint_points_length\fP"
.br
.ti -1c
.RI "\fBsensor_msgs::JointState\fP \fBst_joint_points\fP"
.br
.ti -1c
.RI "\fBsensor_msgs::JointState\fP * \fBjoint_points\fP"
.br
.ti -1c
.RI "bool \fBverbose\fP"
.br
.ti -1c
.RI "\fBcalibration_msgs::DenseLaserSnapshot\fP \fBsnapshot\fP"
.br
.ti -1c
.RI "\fBsensor_msgs::Image\fP \fBlaser_image\fP"
.br
.ti -1c
.RI "\fBcalibration_msgs::CalibrationPattern\fP \fBimage_features\fP"
.br
.ti -1c
.RI "\fBcalibration_msgs::JointStateCalibrationPattern\fP \fBjoint_features\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
