.TH "concert_msgs::ConcertClientState" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
concert_msgs::ConcertClientState \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBPENDING\fP = pending }"
.br
.ti -1c
.RI "enum { \fBBAD\fP = bad }"
.br
.ti -1c
.RI "enum { \fBBLOCKING\fP = blocking }"
.br
.ti -1c
.RI "enum { \fBBUSY\fP = busy }"
.br
.ti -1c
.RI "enum { \fBUNINVITED\fP = uninvited }"
.br
.ti -1c
.RI "enum { \fBJOINING\fP = joining }"
.br
.ti -1c
.RI "enum { \fBAVAILABLE\fP = available }"
.br
.ti -1c
.RI "enum { \fBMISSING\fP = missing }"
.br
.ti -1c
.RI "enum { \fBGONE\fP = gone }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
