.TH "concert_msgs::ConcertClient" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
concert_msgs::ConcertClient \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "const char * \fBgateway_name\fP"
.br
.ti -1c
.RI "\fBrocon_std_msgs::PlatformInfo\fP \fBplatform_info\fP"
.br
.ti -1c
.RI "bool \fBis_local_client\fP"
.br
.ti -1c
.RI "const char * \fBstate\fP"
.br
.ti -1c
.RI "const char * \fBip\fP"
.br
.ti -1c
.RI "\fBgateway_msgs::ConnectionStatistics\fP \fBconn_stats\fP"
.br
.ti -1c
.RI "uint8_t \fBrapps_length\fP"
.br
.ti -1c
.RI "\fBrocon_app_manager_msgs::Rapp\fP \fBst_rapps\fP"
.br
.ti -1c
.RI "\fBrocon_app_manager_msgs::Rapp\fP * \fBrapps\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
