.TH "concert_msgs::ConductorGraph" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
concert_msgs::ConductorGraph \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBpending_length\fP"
.br
.ti -1c
.RI "\fBconcert_msgs::ConcertClient\fP \fBst_pending\fP"
.br
.ti -1c
.RI "\fBconcert_msgs::ConcertClient\fP * \fBpending\fP"
.br
.ti -1c
.RI "uint8_t \fBbad_length\fP"
.br
.ti -1c
.RI "\fBconcert_msgs::ConcertClient\fP \fBst_bad\fP"
.br
.ti -1c
.RI "\fBconcert_msgs::ConcertClient\fP * \fBbad\fP"
.br
.ti -1c
.RI "uint8_t \fBblocking_length\fP"
.br
.ti -1c
.RI "\fBconcert_msgs::ConcertClient\fP \fBst_blocking\fP"
.br
.ti -1c
.RI "\fBconcert_msgs::ConcertClient\fP * \fBblocking\fP"
.br
.ti -1c
.RI "uint8_t \fBbusy_length\fP"
.br
.ti -1c
.RI "\fBconcert_msgs::ConcertClient\fP \fBst_busy\fP"
.br
.ti -1c
.RI "\fBconcert_msgs::ConcertClient\fP * \fBbusy\fP"
.br
.ti -1c
.RI "uint8_t \fBuninvited_length\fP"
.br
.ti -1c
.RI "\fBconcert_msgs::ConcertClient\fP \fBst_uninvited\fP"
.br
.ti -1c
.RI "\fBconcert_msgs::ConcertClient\fP * \fBuninvited\fP"
.br
.ti -1c
.RI "uint8_t \fBjoining_length\fP"
.br
.ti -1c
.RI "\fBconcert_msgs::ConcertClient\fP \fBst_joining\fP"
.br
.ti -1c
.RI "\fBconcert_msgs::ConcertClient\fP * \fBjoining\fP"
.br
.ti -1c
.RI "uint8_t \fBavailable_length\fP"
.br
.ti -1c
.RI "\fBconcert_msgs::ConcertClient\fP \fBst_available\fP"
.br
.ti -1c
.RI "\fBconcert_msgs::ConcertClient\fP * \fBavailable\fP"
.br
.ti -1c
.RI "uint8_t \fBmissing_length\fP"
.br
.ti -1c
.RI "\fBconcert_msgs::ConcertClient\fP \fBst_missing\fP"
.br
.ti -1c
.RI "\fBconcert_msgs::ConcertClient\fP * \fBmissing\fP"
.br
.ti -1c
.RI "uint8_t \fBgone_length\fP"
.br
.ti -1c
.RI "\fBconcert_msgs::ConcertClient\fP \fBst_gone\fP"
.br
.ti -1c
.RI "\fBconcert_msgs::ConcertClient\fP * \fBgone\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
