.TH "concert_msgs::LinkGraph" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
concert_msgs::LinkGraph \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBnodes_length\fP"
.br
.ti -1c
.RI "\fBconcert_msgs::LinkNode\fP \fBst_nodes\fP"
.br
.ti -1c
.RI "\fBconcert_msgs::LinkNode\fP * \fBnodes\fP"
.br
.ti -1c
.RI "uint8_t \fBtopics_length\fP"
.br
.ti -1c
.RI "\fBconcert_msgs::LinkConnection\fP \fBst_topics\fP"
.br
.ti -1c
.RI "\fBconcert_msgs::LinkConnection\fP * \fBtopics\fP"
.br
.ti -1c
.RI "uint8_t \fBactions_length\fP"
.br
.ti -1c
.RI "\fBconcert_msgs::LinkConnection\fP \fBst_actions\fP"
.br
.ti -1c
.RI "\fBconcert_msgs::LinkConnection\fP * \fBactions\fP"
.br
.ti -1c
.RI "uint8_t \fBservices_length\fP"
.br
.ti -1c
.RI "\fBconcert_msgs::LinkConnection\fP \fBst_services\fP"
.br
.ti -1c
.RI "\fBconcert_msgs::LinkConnection\fP * \fBservices\fP"
.br
.ti -1c
.RI "uint8_t \fBedges_length\fP"
.br
.ti -1c
.RI "\fBconcert_msgs::LinkEdge\fP \fBst_edges\fP"
.br
.ti -1c
.RI "\fBconcert_msgs::LinkEdge\fP * \fBedges\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
