.TH "controller_manager_msgs::ListControllerTypesResponse" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
controller_manager_msgs::ListControllerTypesResponse \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBtypes_length\fP"
.br
.ti -1c
.RI "char * \fBst_types\fP"
.br
.ti -1c
.RI "char ** \fBtypes\fP"
.br
.ti -1c
.RI "uint8_t \fBbase_classes_length\fP"
.br
.ti -1c
.RI "char * \fBst_base_classes\fP"
.br
.ti -1c
.RI "char ** \fBbase_classes\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
