.TH "control_msgs::JointControllerState" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
control_msgs::JointControllerState \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd_msgs::Header\fP \fBheader\fP"
.br
.ti -1c
.RI "float \fBset_point\fP"
.br
.ti -1c
.RI "float \fBprocess_value\fP"
.br
.ti -1c
.RI "float \fBprocess_value_dot\fP"
.br
.ti -1c
.RI "float \fBerror\fP"
.br
.ti -1c
.RI "float \fBtime_step\fP"
.br
.ti -1c
.RI "float \fBcommand\fP"
.br
.ti -1c
.RI "float \fBp\fP"
.br
.ti -1c
.RI "float \fBi\fP"
.br
.ti -1c
.RI "float \fBd\fP"
.br
.ti -1c
.RI "float \fBi_clamp\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
