.TH "dynamixel_controllers::RestartControllerRequest" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dynamixel_controllers::RestartControllerRequest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBport_name\fP"
.br
.ti -1c
.RI "const char * \fBpackage_path\fP"
.br
.ti -1c
.RI "const char * \fBmodule_name\fP"
.br
.ti -1c
.RI "const char * \fBclass_name\fP"
.br
.ti -1c
.RI "const char * \fBcontroller_name\fP"
.br
.ti -1c
.RI "uint8_t \fBdependencies_length\fP"
.br
.ti -1c
.RI "char * \fBst_dependencies\fP"
.br
.ti -1c
.RI "char ** \fBdependencies\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
