.TH "ethercat_hardware::ActuatorInfo" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ethercat_hardware::ActuatorInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBid\fP"
.br
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "const char * \fBrobot_name\fP"
.br
.ti -1c
.RI "const char * \fBmotor_make\fP"
.br
.ti -1c
.RI "const char * \fBmotor_model\fP"
.br
.ti -1c
.RI "float \fBmax_current\fP"
.br
.ti -1c
.RI "float \fBspeed_constant\fP"
.br
.ti -1c
.RI "float \fBmotor_resistance\fP"
.br
.ti -1c
.RI "float \fBmotor_torque_constant\fP"
.br
.ti -1c
.RI "float \fBencoder_reduction\fP"
.br
.ti -1c
.RI "float \fBpulses_per_revolution\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
