.TH "ethercat_trigger_controllers::SetMultiWaveform" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ethercat_trigger_controllers::SetMultiWaveform \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBSetMultiWaveformRequest\fP \fBRequest\fP"
.br
.ti -1c
.RI "typedef \fBSetMultiWaveformResponse\fP \fBResponse\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
