.TH "ethercat_hardware::RawFTData" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ethercat_hardware::RawFTData \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBsamples_length\fP"
.br
.ti -1c
.RI "\fBethercat_hardware::RawFTDataSample\fP \fBst_samples\fP"
.br
.ti -1c
.RI "\fBethercat_hardware::RawFTDataSample\fP * \fBsamples\fP"
.br
.ti -1c
.RI "int64_t \fBsample_count\fP"
.br
.ti -1c
.RI "int64_t \fBmissed_samples\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
