.TH "ethercat_hardware::BoardInfo" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ethercat_hardware::BoardInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBdescription\fP"
.br
.ti -1c
.RI "uint32_t \fBproduct_code\fP"
.br
.ti -1c
.RI "uint32_t \fBpcb\fP"
.br
.ti -1c
.RI "uint32_t \fBpca\fP"
.br
.ti -1c
.RI "uint32_t \fBserial\fP"
.br
.ti -1c
.RI "uint32_t \fBfirmware_major\fP"
.br
.ti -1c
.RI "uint32_t \fBfirmware_minor\fP"
.br
.ti -1c
.RI "float \fBboard_resistance\fP"
.br
.ti -1c
.RI "float \fBmax_pwm_ratio\fP"
.br
.ti -1c
.RI "float \fBhw_max_current\fP"
.br
.ti -1c
.RI "bool \fBpoor_measured_motor_voltage\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
