.TH "fetch_driver_msgs::BoardState" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fetch_driver_msgs::BoardState \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "int32_t \fBboard_type\fP"
.br
.ti -1c
.RI "int16_t \fBboard_revision\fP"
.br
.ti -1c
.RI "int16_t \fBsoftware_revision\fP"
.br
.ti -1c
.RI "int8_t \fBboot_status\fP"
.br
.ti -1c
.RI "uint16_t \fBboard_flags\fP"
.br
.ti -1c
.RI "uint64_t \fBsystem_time\fP"
.br
.ti -1c
.RI "float \fBvoltage\fP"
.br
.ti -1c
.RI "float \fBtemperature\fP"
.br
.ti -1c
.RI "uint32_t \fBpackets_sent\fP"
.br
.ti -1c
.RI "uint32_t \fBpackets_recv\fP"
.br
.ti -1c
.RI "uint32_t \fBpackets_bad\fP"
.br
.ti -1c
.RI "uint32_t \fBpackets_back\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
