.TH "fetch_driver_msgs::ChargerState" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fetch_driver_msgs::ChargerState \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBstate\fP"
.br
.ti -1c
.RI "uint8_t \fBerror\fP"
.br
.ti -1c
.RI "uint8_t \fBcharging_mode\fP"
.br
.ti -1c
.RI "uint8_t \fBlimit_cause\fP"
.br
.ti -1c
.RI "uint8_t \fBbalancing_mode\fP"
.br
.ti -1c
.RI "float \fBbattery_voltage\fP"
.br
.ti -1c
.RI "float \fBbattery_half_voltage\fP"
.br
.ti -1c
.RI "float \fBcharger_voltage\fP"
.br
.ti -1c
.RI "float \fBsupply_voltage\fP"
.br
.ti -1c
.RI "float \fBphase1_current\fP"
.br
.ti -1c
.RI "float \fBphase2_current\fP"
.br
.ti -1c
.RI "float \fBcharger_temp\fP"
.br
.ti -1c
.RI "float \fBbattery_temp\fP"
.br
.ti -1c
.RI "float \fBsupply_connector_temp\fP"
.br
.ti -1c
.RI "float \fBfan_speed\fP"
.br
.ti -1c
.RI "float \fBbattery_capacity\fP"
.br
.ti -1c
.RI "float \fBbattery_energy\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
