.TH "fingertip_pressure::PressureInfoElement" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fingertip_pressure::PressureInfoElement \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBframe_id\fP"
.br
.ti -1c
.RI "uint8_t \fBcenter_length\fP"
.br
.ti -1c
.RI "\fBgeometry_msgs::Vector3\fP \fBst_center\fP"
.br
.ti -1c
.RI "\fBgeometry_msgs::Vector3\fP * \fBcenter\fP"
.br
.ti -1c
.RI "uint8_t \fBhalfside1_length\fP"
.br
.ti -1c
.RI "\fBgeometry_msgs::Vector3\fP \fBst_halfside1\fP"
.br
.ti -1c
.RI "\fBgeometry_msgs::Vector3\fP * \fBhalfside1\fP"
.br
.ti -1c
.RI "uint8_t \fBhalfside2_length\fP"
.br
.ti -1c
.RI "\fBgeometry_msgs::Vector3\fP \fBst_halfside2\fP"
.br
.ti -1c
.RI "\fBgeometry_msgs::Vector3\fP * \fBhalfside2\fP"
.br
.ti -1c
.RI "uint8_t \fBforce_per_unit_length\fP"
.br
.ti -1c
.RI "float \fBst_force_per_unit\fP"
.br
.ti -1c
.RI "float * \fBforce_per_unit\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
