.TH "gazebo_msgs::ODEJointProperties" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gazebo_msgs::ODEJointProperties \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBdamping_length\fP"
.br
.ti -1c
.RI "float \fBst_damping\fP"
.br
.ti -1c
.RI "float * \fBdamping\fP"
.br
.ti -1c
.RI "uint8_t \fBhiStop_length\fP"
.br
.ti -1c
.RI "float \fBst_hiStop\fP"
.br
.ti -1c
.RI "float * \fBhiStop\fP"
.br
.ti -1c
.RI "uint8_t \fBloStop_length\fP"
.br
.ti -1c
.RI "float \fBst_loStop\fP"
.br
.ti -1c
.RI "float * \fBloStop\fP"
.br
.ti -1c
.RI "uint8_t \fBerp_length\fP"
.br
.ti -1c
.RI "float \fBst_erp\fP"
.br
.ti -1c
.RI "float * \fBerp\fP"
.br
.ti -1c
.RI "uint8_t \fBcfm_length\fP"
.br
.ti -1c
.RI "float \fBst_cfm\fP"
.br
.ti -1c
.RI "float * \fBcfm\fP"
.br
.ti -1c
.RI "uint8_t \fBstop_erp_length\fP"
.br
.ti -1c
.RI "float \fBst_stop_erp\fP"
.br
.ti -1c
.RI "float * \fBstop_erp\fP"
.br
.ti -1c
.RI "uint8_t \fBstop_cfm_length\fP"
.br
.ti -1c
.RI "float \fBst_stop_cfm\fP"
.br
.ti -1c
.RI "float * \fBstop_cfm\fP"
.br
.ti -1c
.RI "uint8_t \fBfudge_factor_length\fP"
.br
.ti -1c
.RI "float \fBst_fudge_factor\fP"
.br
.ti -1c
.RI "float * \fBfudge_factor\fP"
.br
.ti -1c
.RI "uint8_t \fBfmax_length\fP"
.br
.ti -1c
.RI "float \fBst_fmax\fP"
.br
.ti -1c
.RI "float * \fBfmax\fP"
.br
.ti -1c
.RI "uint8_t \fBvel_length\fP"
.br
.ti -1c
.RI "float \fBst_vel\fP"
.br
.ti -1c
.RI "float * \fBvel\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
