.TH "gazebo_msgs::ODEPhysics" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gazebo_msgs::ODEPhysics \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBauto_disable_bodies\fP"
.br
.ti -1c
.RI "uint32_t \fBsor_pgs_precon_iters\fP"
.br
.ti -1c
.RI "uint32_t \fBsor_pgs_iters\fP"
.br
.ti -1c
.RI "float \fBsor_pgs_w\fP"
.br
.ti -1c
.RI "float \fBsor_pgs_rms_error_tol\fP"
.br
.ti -1c
.RI "float \fBcontact_surface_layer\fP"
.br
.ti -1c
.RI "float \fBcontact_max_correcting_vel\fP"
.br
.ti -1c
.RI "float \fBcfm\fP"
.br
.ti -1c
.RI "float \fBerp\fP"
.br
.ti -1c
.RI "uint32_t \fBmax_contacts\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
