.TH "geographic_msgs::MapFeature" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
geographic_msgs::MapFeature \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBuuid_msgs::UniqueID\fP \fBid\fP"
.br
.ti -1c
.RI "uint8_t \fBcomponents_length\fP"
.br
.ti -1c
.RI "\fBuuid_msgs::UniqueID\fP \fBst_components\fP"
.br
.ti -1c
.RI "\fBuuid_msgs::UniqueID\fP * \fBcomponents\fP"
.br
.ti -1c
.RI "uint8_t \fBprops_length\fP"
.br
.ti -1c
.RI "\fBgeographic_msgs::KeyValue\fP \fBst_props\fP"
.br
.ti -1c
.RI "\fBgeographic_msgs::KeyValue\fP * \fBprops\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
