.TH "geographic_msgs::RouteNetwork" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
geographic_msgs::RouteNetwork \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd_msgs::Header\fP \fBheader\fP"
.br
.ti -1c
.RI "\fBuuid_msgs::UniqueID\fP \fBid\fP"
.br
.ti -1c
.RI "\fBgeographic_msgs::BoundingBox\fP \fBbounds\fP"
.br
.ti -1c
.RI "uint8_t \fBpoints_length\fP"
.br
.ti -1c
.RI "\fBgeographic_msgs::WayPoint\fP \fBst_points\fP"
.br
.ti -1c
.RI "\fBgeographic_msgs::WayPoint\fP * \fBpoints\fP"
.br
.ti -1c
.RI "uint8_t \fBsegments_length\fP"
.br
.ti -1c
.RI "\fBgeographic_msgs::RouteSegment\fP \fBst_segments\fP"
.br
.ti -1c
.RI "\fBgeographic_msgs::RouteSegment\fP * \fBsegments\fP"
.br
.ti -1c
.RI "uint8_t \fBprops_length\fP"
.br
.ti -1c
.RI "\fBgeographic_msgs::KeyValue\fP \fBst_props\fP"
.br
.ti -1c
.RI "\fBgeographic_msgs::KeyValue\fP * \fBprops\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
