.TH "hector_nav_msgs::GetRecoveryInfo" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hector_nav_msgs::GetRecoveryInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBGetRecoveryInfoRequest\fP \fBRequest\fP"
.br
.ti -1c
.RI "typedef \fBGetRecoveryInfoResponse\fP \fBResponse\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
