.TH "household_objects_database_msgs::SaveScanRequest" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
household_objects_database_msgs::SaveScanRequest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int32_t \fBscaled_model_id\fP"
.br
.ti -1c
.RI "\fBgeometry_msgs::PoseStamped\fP \fBground_truth_pose\fP"
.br
.ti -1c
.RI "const char * \fBbagfile_location\fP"
.br
.ti -1c
.RI "const char * \fBscan_source\fP"
.br
.ti -1c
.RI "const char * \fBcloud_topic\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
