.TH "household_objects_database_msgs::GetModelList" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
household_objects_database_msgs::GetModelList \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBGetModelListRequest\fP \fBRequest\fP"
.br
.ti -1c
.RI "typedef \fBGetModelListResponse\fP \fBResponse\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
