.TH "husky_msgs::HuskyStatus" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
husky_msgs::HuskyStatus \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd_msgs::Header\fP \fBheader\fP"
.br
.ti -1c
.RI "uint32_t \fBuptime\fP"
.br
.ti -1c
.RI "float \fBros_control_loop_freq\fP"
.br
.ti -1c
.RI "float \fBmcu_and_user_port_current\fP"
.br
.ti -1c
.RI "float \fBleft_driver_current\fP"
.br
.ti -1c
.RI "float \fBright_driver_current\fP"
.br
.ti -1c
.RI "float \fBbattery_voltage\fP"
.br
.ti -1c
.RI "float \fBleft_driver_voltage\fP"
.br
.ti -1c
.RI "float \fBright_driver_voltage\fP"
.br
.ti -1c
.RI "float \fBleft_driver_temp\fP"
.br
.ti -1c
.RI "float \fBright_driver_temp\fP"
.br
.ti -1c
.RI "float \fBleft_motor_temp\fP"
.br
.ti -1c
.RI "float \fBright_motor_temp\fP"
.br
.ti -1c
.RI "uint16_t \fBcapacity_estimate\fP"
.br
.ti -1c
.RI "float \fBcharge_estimate\fP"
.br
.ti -1c
.RI "bool \fBtimeout\fP"
.br
.ti -1c
.RI "bool \fBlockout\fP"
.br
.ti -1c
.RI "bool \fBe_stop\fP"
.br
.ti -1c
.RI "bool \fBros_pause\fP"
.br
.ti -1c
.RI "bool \fBno_battery\fP"
.br
.ti -1c
.RI "bool \fBcurrent_limit\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
