.TH "jackal_msgs::Status" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jackal_msgs::Status \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd_msgs::Header\fP \fBheader\fP"
.br
.ti -1c
.RI "const char * \fBhardware_id\fP"
.br
.ti -1c
.RI "\fBros::Duration\fP \fBmcu_uptime\fP"
.br
.ti -1c
.RI "\fBros::Duration\fP \fBconnection_uptime\fP"
.br
.ti -1c
.RI "bool \fBdrivers_active\fP"
.br
.ti -1c
.RI "bool \fBdriver_external_stop_present\fP"
.br
.ti -1c
.RI "bool \fBdriver_external_stop_stopped\fP"
.br
.ti -1c
.RI "float \fBmeasured_battery\fP"
.br
.ti -1c
.RI "float \fBmeasured_12v\fP"
.br
.ti -1c
.RI "float \fBmeasured_5v\fP"
.br
.ti -1c
.RI "float \fBdrive_current\fP"
.br
.ti -1c
.RI "float \fBuser_current\fP"
.br
.ti -1c
.RI "float \fBcomputer_current\fP"
.br
.ti -1c
.RI "float \fBtotal_current\fP"
.br
.ti -1c
.RI "float \fBtotal_current_peak\fP"
.br
.ti -1c
.RI "float \fBtotal_power_consumed\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
