.TH "jackal_msgs::Drive" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jackal_msgs::Drive \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBMODE_VELOCITY\fP = 0 }"
.br
.ti -1c
.RI "enum { \fBMODE_PWM\fP = 1 }"
.br
.ti -1c
.RI "enum { \fBMODE_EFFORT\fP = 2 }"
.br
.ti -1c
.RI "enum { \fBMODE_NONE\fP = -1 }"
.br
.ti -1c
.RI "enum { \fBLEFT\fP = 0 }"
.br
.ti -1c
.RI "enum { \fBRIGHT\fP = 1 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int8_t \fBmode\fP"
.br
.ti -1c
.RI "float \fBdrivers\fP [2]"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
