.TH "joint_qualification_controllers::HysteresisData" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
joint_qualification_controllers::HysteresisData \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBjoint_name\fP"
.br
.ti -1c
.RI "uint8_t \fBtime_up_length\fP"
.br
.ti -1c
.RI "float \fBst_time_up\fP"
.br
.ti -1c
.RI "float * \fBtime_up\fP"
.br
.ti -1c
.RI "uint8_t \fBeffort_up_length\fP"
.br
.ti -1c
.RI "float \fBst_effort_up\fP"
.br
.ti -1c
.RI "float * \fBeffort_up\fP"
.br
.ti -1c
.RI "uint8_t \fBposition_up_length\fP"
.br
.ti -1c
.RI "float \fBst_position_up\fP"
.br
.ti -1c
.RI "float * \fBposition_up\fP"
.br
.ti -1c
.RI "uint8_t \fBvelocity_up_length\fP"
.br
.ti -1c
.RI "float \fBst_velocity_up\fP"
.br
.ti -1c
.RI "float * \fBvelocity_up\fP"
.br
.ti -1c
.RI "uint8_t \fBtime_down_length\fP"
.br
.ti -1c
.RI "float \fBst_time_down\fP"
.br
.ti -1c
.RI "float * \fBtime_down\fP"
.br
.ti -1c
.RI "uint8_t \fBeffort_down_length\fP"
.br
.ti -1c
.RI "float \fBst_effort_down\fP"
.br
.ti -1c
.RI "float * \fBeffort_down\fP"
.br
.ti -1c
.RI "uint8_t \fBposition_down_length\fP"
.br
.ti -1c
.RI "float \fBst_position_down\fP"
.br
.ti -1c
.RI "float * \fBposition_down\fP"
.br
.ti -1c
.RI "uint8_t \fBvelocity_down_length\fP"
.br
.ti -1c
.RI "float \fBst_velocity_down\fP"
.br
.ti -1c
.RI "float * \fBvelocity_down\fP"
.br
.ti -1c
.RI "uint8_t \fBarg_name_length\fP"
.br
.ti -1c
.RI "char * \fBst_arg_name\fP"
.br
.ti -1c
.RI "char ** \fBarg_name\fP"
.br
.ti -1c
.RI "uint8_t \fBarg_value_length\fP"
.br
.ti -1c
.RI "float \fBst_arg_value\fP"
.br
.ti -1c
.RI "float * \fBarg_value\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
