.TH "joint_qualification_controllers::WristRollTurn" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
joint_qualification_controllers::WristRollTurn \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBtime_length\fP"
.br
.ti -1c
.RI "float \fBst_time\fP"
.br
.ti -1c
.RI "float * \fBtime\fP"
.br
.ti -1c
.RI "uint8_t \fBflex_position_length\fP"
.br
.ti -1c
.RI "float \fBst_flex_position\fP"
.br
.ti -1c
.RI "float * \fBflex_position\fP"
.br
.ti -1c
.RI "uint8_t \fBflex_effort_length\fP"
.br
.ti -1c
.RI "float \fBst_flex_effort\fP"
.br
.ti -1c
.RI "float * \fBflex_effort\fP"
.br
.ti -1c
.RI "uint8_t \fBflex_cmd_length\fP"
.br
.ti -1c
.RI "float \fBst_flex_cmd\fP"
.br
.ti -1c
.RI "float * \fBflex_cmd\fP"
.br
.ti -1c
.RI "uint8_t \fBroll_position_length\fP"
.br
.ti -1c
.RI "float \fBst_roll_position\fP"
.br
.ti -1c
.RI "float * \fBroll_position\fP"
.br
.ti -1c
.RI "uint8_t \fBroll_effort_length\fP"
.br
.ti -1c
.RI "float \fBst_roll_effort\fP"
.br
.ti -1c
.RI "float * \fBroll_effort\fP"
.br
.ti -1c
.RI "uint8_t \fBroll_cmd_length\fP"
.br
.ti -1c
.RI "float \fBst_roll_cmd\fP"
.br
.ti -1c
.RI "float * \fBroll_cmd\fP"
.br
.ti -1c
.RI "uint8_t \fBroll_velocity_length\fP"
.br
.ti -1c
.RI "float \fBst_roll_velocity\fP"
.br
.ti -1c
.RI "float * \fBroll_velocity\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
