.TH "joint_qualification_controllers::HysteresisRun" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
joint_qualification_controllers::HysteresisRun \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBUP\fP = 0 }"
.br
.ti -1c
.RI "enum { \fBDOWN\fP = 1 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBtime_length\fP"
.br
.ti -1c
.RI "float \fBst_time\fP"
.br
.ti -1c
.RI "float * \fBtime\fP"
.br
.ti -1c
.RI "uint8_t \fBeffort_length\fP"
.br
.ti -1c
.RI "float \fBst_effort\fP"
.br
.ti -1c
.RI "float * \fBeffort\fP"
.br
.ti -1c
.RI "uint8_t \fBposition_length\fP"
.br
.ti -1c
.RI "float \fBst_position\fP"
.br
.ti -1c
.RI "float * \fBposition\fP"
.br
.ti -1c
.RI "uint8_t \fBvelocity_length\fP"
.br
.ti -1c
.RI "float \fBst_velocity\fP"
.br
.ti -1c
.RI "float * \fBvelocity\fP"
.br
.ti -1c
.RI "uint8_t \fBdir\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
