.TH "jsk_recognition_msgs::ClassificationResult" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jsk_recognition_msgs::ClassificationResult \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd_msgs::Header\fP \fBheader\fP"
.br
.ti -1c
.RI "uint8_t \fBlabels_length\fP"
.br
.ti -1c
.RI "uint32_t \fBst_labels\fP"
.br
.ti -1c
.RI "uint32_t * \fBlabels\fP"
.br
.ti -1c
.RI "uint8_t \fBlabel_names_length\fP"
.br
.ti -1c
.RI "char * \fBst_label_names\fP"
.br
.ti -1c
.RI "char ** \fBlabel_names\fP"
.br
.ti -1c
.RI "uint8_t \fBlabel_proba_length\fP"
.br
.ti -1c
.RI "float \fBst_label_proba\fP"
.br
.ti -1c
.RI "float * \fBlabel_proba\fP"
.br
.ti -1c
.RI "uint8_t \fBprobabilities_length\fP"
.br
.ti -1c
.RI "float \fBst_probabilities\fP"
.br
.ti -1c
.RI "float * \fBprobabilities\fP"
.br
.ti -1c
.RI "const char * \fBclassifier\fP"
.br
.ti -1c
.RI "uint8_t \fBtarget_names_length\fP"
.br
.ti -1c
.RI "char * \fBst_target_names\fP"
.br
.ti -1c
.RI "char ** \fBtarget_names\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
