.TH "jsk_footstep_msgs::Footstep" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jsk_footstep_msgs::Footstep \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBRIGHT\fP = 2 }"
.br
.ti -1c
.RI "enum { \fBLEFT\fP = 1 }"
.br
.ti -1c
.RI "enum { \fBREJECTED\fP = 3 }"
.br
.ti -1c
.RI "enum { \fBAPPROVED\fP = 4 }"
.br
.ti -1c
.RI "enum { \fBLLEG\fP = 1 }"
.br
.ti -1c
.RI "enum { \fBRLEG\fP = 2 }"
.br
.ti -1c
.RI "enum { \fBLARM\fP = 5 }"
.br
.ti -1c
.RI "enum { \fBRARM\fP = 6 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBleg\fP"
.br
.ti -1c
.RI "\fBgeometry_msgs::Pose\fP \fBpose\fP"
.br
.ti -1c
.RI "\fBros::Duration\fP \fBduration\fP"
.br
.ti -1c
.RI "uint32_t \fBfootstep_group\fP"
.br
.ti -1c
.RI "\fBgeometry_msgs::Vector3\fP \fBdimensions\fP"
.br
.ti -1c
.RI "float \fBswing_height\fP"
.br
.ti -1c
.RI "float \fBcost\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
