.TH "jsk_recognition_msgs::PolygonArray" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jsk_recognition_msgs::PolygonArray \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd_msgs::Header\fP \fBheader\fP"
.br
.ti -1c
.RI "uint8_t \fBpolygons_length\fP"
.br
.ti -1c
.RI "\fBgeometry_msgs::PolygonStamped\fP \fBst_polygons\fP"
.br
.ti -1c
.RI "\fBgeometry_msgs::PolygonStamped\fP * \fBpolygons\fP"
.br
.ti -1c
.RI "uint8_t \fBlabels_length\fP"
.br
.ti -1c
.RI "uint32_t \fBst_labels\fP"
.br
.ti -1c
.RI "uint32_t * \fBlabels\fP"
.br
.ti -1c
.RI "uint8_t \fBlikelihood_length\fP"
.br
.ti -1c
.RI "float \fBst_likelihood\fP"
.br
.ti -1c
.RI "float * \fBlikelihood\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
