.TH "kobuki_msgs::DockInfraRed" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kobuki_msgs::DockInfraRed \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBNEAR_LEFT\fP = 1 }"
.br
.ti -1c
.RI "enum { \fBNEAR_CENTER\fP = 2 }"
.br
.ti -1c
.RI "enum { \fBNEAR_RIGHT\fP = 4 }"
.br
.ti -1c
.RI "enum { \fBFAR_LEFT\fP = 16 }"
.br
.ti -1c
.RI "enum { \fBFAR_CENTER\fP = 8 }"
.br
.ti -1c
.RI "enum { \fBFAR_RIGHT\fP = 32 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd_msgs::Header\fP \fBheader\fP"
.br
.ti -1c
.RI "uint8_t \fBdata_length\fP"
.br
.ti -1c
.RI "uint8_t \fBst_data\fP"
.br
.ti -1c
.RI "uint8_t * \fBdata\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
