.TH "kobuki_msgs::BumperEvent" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kobuki_msgs::BumperEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBLEFT\fP = 0 }"
.br
.ti -1c
.RI "enum { \fBCENTER\fP = 1 }"
.br
.ti -1c
.RI "enum { \fBRIGHT\fP = 2 }"
.br
.ti -1c
.RI "enum { \fBRELEASED\fP = 0 }"
.br
.ti -1c
.RI "enum { \fBPRESSED\fP = 1 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBbumper\fP"
.br
.ti -1c
.RI "uint8_t \fBstate\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
