.TH "laser_assembler::AssembleScans2" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
laser_assembler::AssembleScans2 \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBAssembleScans2Request\fP \fBRequest\fP"
.br
.ti -1c
.RI "typedef \fBAssembleScans2Response\fP \fBResponse\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
