.TH "manipulation_msgs::SceneRegion" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
manipulation_msgs::SceneRegion \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsensor_msgs::PointCloud2\fP \fBcloud\fP"
.br
.ti -1c
.RI "uint8_t \fBmask_length\fP"
.br
.ti -1c
.RI "int32_t \fBst_mask\fP"
.br
.ti -1c
.RI "int32_t * \fBmask\fP"
.br
.ti -1c
.RI "\fBsensor_msgs::Image\fP \fBimage\fP"
.br
.ti -1c
.RI "\fBsensor_msgs::Image\fP \fBdisparity_image\fP"
.br
.ti -1c
.RI "\fBsensor_msgs::CameraInfo\fP \fBcam_info\fP"
.br
.ti -1c
.RI "\fBgeometry_msgs::PoseStamped\fP \fBroi_box_pose\fP"
.br
.ti -1c
.RI "\fBgeometry_msgs::Vector3\fP \fBroi_box_dims\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
