.TH "manipulation_msgs::GraspPlanningRequest" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
manipulation_msgs::GraspPlanningRequest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBarm_name\fP"
.br
.ti -1c
.RI "\fBmanipulation_msgs::GraspableObject\fP \fBtarget\fP"
.br
.ti -1c
.RI "const char * \fBcollision_object_name\fP"
.br
.ti -1c
.RI "const char * \fBcollision_support_surface_name\fP"
.br
.ti -1c
.RI "uint8_t \fBgrasps_to_evaluate_length\fP"
.br
.ti -1c
.RI "\fBmanipulation_msgs::Grasp\fP \fBst_grasps_to_evaluate\fP"
.br
.ti -1c
.RI "\fBmanipulation_msgs::Grasp\fP * \fBgrasps_to_evaluate\fP"
.br
.ti -1c
.RI "uint8_t \fBmovable_obstacles_length\fP"
.br
.ti -1c
.RI "\fBmanipulation_msgs::GraspableObject\fP \fBst_movable_obstacles\fP"
.br
.ti -1c
.RI "\fBmanipulation_msgs::GraspableObject\fP * \fBmovable_obstacles\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
