.TH "moveit_msgs::GetStateValidityResponse" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moveit_msgs::GetStateValidityResponse \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBvalid\fP"
.br
.ti -1c
.RI "uint8_t \fBcontacts_length\fP"
.br
.ti -1c
.RI "\fBmoveit_msgs::ContactInformation\fP \fBst_contacts\fP"
.br
.ti -1c
.RI "\fBmoveit_msgs::ContactInformation\fP * \fBcontacts\fP"
.br
.ti -1c
.RI "uint8_t \fBcost_sources_length\fP"
.br
.ti -1c
.RI "\fBmoveit_msgs::CostSource\fP \fBst_cost_sources\fP"
.br
.ti -1c
.RI "\fBmoveit_msgs::CostSource\fP * \fBcost_sources\fP"
.br
.ti -1c
.RI "uint8_t \fBconstraint_result_length\fP"
.br
.ti -1c
.RI "\fBmoveit_msgs::ConstraintEvalResult\fP \fBst_constraint_result\fP"
.br
.ti -1c
.RI "\fBmoveit_msgs::ConstraintEvalResult\fP * \fBconstraint_result\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
