.TH "moveit_msgs::AllowedCollisionMatrix" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moveit_msgs::AllowedCollisionMatrix \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBentry_names_length\fP"
.br
.ti -1c
.RI "char * \fBst_entry_names\fP"
.br
.ti -1c
.RI "char ** \fBentry_names\fP"
.br
.ti -1c
.RI "uint8_t \fBentry_values_length\fP"
.br
.ti -1c
.RI "\fBmoveit_msgs::AllowedCollisionEntry\fP \fBst_entry_values\fP"
.br
.ti -1c
.RI "\fBmoveit_msgs::AllowedCollisionEntry\fP * \fBentry_values\fP"
.br
.ti -1c
.RI "uint8_t \fBdefault_entry_names_length\fP"
.br
.ti -1c
.RI "char * \fBst_default_entry_names\fP"
.br
.ti -1c
.RI "char ** \fBdefault_entry_names\fP"
.br
.ti -1c
.RI "uint8_t \fBdefault_entry_values_length\fP"
.br
.ti -1c
.RI "bool \fBst_default_entry_values\fP"
.br
.ti -1c
.RI "bool * \fBdefault_entry_values\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
