.TH "moveit_msgs::Constraints" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moveit_msgs::Constraints \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "uint8_t \fBjoint_constraints_length\fP"
.br
.ti -1c
.RI "\fBmoveit_msgs::JointConstraint\fP \fBst_joint_constraints\fP"
.br
.ti -1c
.RI "\fBmoveit_msgs::JointConstraint\fP * \fBjoint_constraints\fP"
.br
.ti -1c
.RI "uint8_t \fBposition_constraints_length\fP"
.br
.ti -1c
.RI "\fBmoveit_msgs::PositionConstraint\fP \fBst_position_constraints\fP"
.br
.ti -1c
.RI "\fBmoveit_msgs::PositionConstraint\fP * \fBposition_constraints\fP"
.br
.ti -1c
.RI "uint8_t \fBorientation_constraints_length\fP"
.br
.ti -1c
.RI "\fBmoveit_msgs::OrientationConstraint\fP \fBst_orientation_constraints\fP"
.br
.ti -1c
.RI "\fBmoveit_msgs::OrientationConstraint\fP * \fBorientation_constraints\fP"
.br
.ti -1c
.RI "uint8_t \fBvisibility_constraints_length\fP"
.br
.ti -1c
.RI "\fBmoveit_msgs::VisibilityConstraint\fP \fBst_visibility_constraints\fP"
.br
.ti -1c
.RI "\fBmoveit_msgs::VisibilityConstraint\fP * \fBvisibility_constraints\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
