.TH "opencv_apps::Moment" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
opencv_apps::Moment \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBm00\fP"
.br
.ti -1c
.RI "float \fBm10\fP"
.br
.ti -1c
.RI "float \fBm01\fP"
.br
.ti -1c
.RI "float \fBm20\fP"
.br
.ti -1c
.RI "float \fBm11\fP"
.br
.ti -1c
.RI "float \fBm02\fP"
.br
.ti -1c
.RI "float \fBm30\fP"
.br
.ti -1c
.RI "float \fBm21\fP"
.br
.ti -1c
.RI "float \fBm12\fP"
.br
.ti -1c
.RI "float \fBm03\fP"
.br
.ti -1c
.RI "float \fBmu20\fP"
.br
.ti -1c
.RI "float \fBmu11\fP"
.br
.ti -1c
.RI "float \fBmu02\fP"
.br
.ti -1c
.RI "float \fBmu30\fP"
.br
.ti -1c
.RI "float \fBmu21\fP"
.br
.ti -1c
.RI "float \fBmu12\fP"
.br
.ti -1c
.RI "float \fBmu03\fP"
.br
.ti -1c
.RI "float \fBnu20\fP"
.br
.ti -1c
.RI "float \fBnu11\fP"
.br
.ti -1c
.RI "float \fBnu02\fP"
.br
.ti -1c
.RI "float \fBnu30\fP"
.br
.ti -1c
.RI "float \fBnu21\fP"
.br
.ti -1c
.RI "float \fBnu12\fP"
.br
.ti -1c
.RI "float \fBnu03\fP"
.br
.ti -1c
.RI "\fBopencv_apps::Point2D\fP \fBcenter\fP"
.br
.ti -1c
.RI "float \fBlength\fP"
.br
.ti -1c
.RI "float \fBarea\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
