.TH "play_motion_msgs::ListMotions" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
play_motion_msgs::ListMotions \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBListMotionsRequest\fP \fBRequest\fP"
.br
.ti -1c
.RI "typedef \fBListMotionsResponse\fP \fBResponse\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
