.TH "posedetection_msgs::Feature0D" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
posedetection_msgs::Feature0D \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd_msgs::Header\fP \fBheader\fP"
.br
.ti -1c
.RI "uint8_t \fBpositions_length\fP"
.br
.ti -1c
.RI "float \fBst_positions\fP"
.br
.ti -1c
.RI "float * \fBpositions\fP"
.br
.ti -1c
.RI "uint8_t \fBscales_length\fP"
.br
.ti -1c
.RI "float \fBst_scales\fP"
.br
.ti -1c
.RI "float * \fBscales\fP"
.br
.ti -1c
.RI "uint8_t \fBorientations_length\fP"
.br
.ti -1c
.RI "float \fBst_orientations\fP"
.br
.ti -1c
.RI "float * \fBorientations\fP"
.br
.ti -1c
.RI "uint8_t \fBconfidences_length\fP"
.br
.ti -1c
.RI "float \fBst_confidences\fP"
.br
.ti -1c
.RI "float * \fBconfidences\fP"
.br
.ti -1c
.RI "uint8_t \fBdescriptors_length\fP"
.br
.ti -1c
.RI "float \fBst_descriptors\fP"
.br
.ti -1c
.RI "float * \fBdescriptors\fP"
.br
.ti -1c
.RI "int32_t \fBdescriptor_dim\fP"
.br
.ti -1c
.RI "const char * \fBtype\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
