.TH "pr2_mechanism_msgs::ActuatorStatistics" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pr2_mechanism_msgs::ActuatorStatistics \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "int32_t \fBdevice_id\fP"
.br
.ti -1c
.RI "\fBros::Time\fP \fBtimestamp\fP"
.br
.ti -1c
.RI "int32_t \fBencoder_count\fP"
.br
.ti -1c
.RI "float \fBencoder_offset\fP"
.br
.ti -1c
.RI "float \fBposition\fP"
.br
.ti -1c
.RI "float \fBencoder_velocity\fP"
.br
.ti -1c
.RI "float \fBvelocity\fP"
.br
.ti -1c
.RI "bool \fBcalibration_reading\fP"
.br
.ti -1c
.RI "bool \fBcalibration_rising_edge_valid\fP"
.br
.ti -1c
.RI "bool \fBcalibration_falling_edge_valid\fP"
.br
.ti -1c
.RI "float \fBlast_calibration_rising_edge\fP"
.br
.ti -1c
.RI "float \fBlast_calibration_falling_edge\fP"
.br
.ti -1c
.RI "bool \fBis_enabled\fP"
.br
.ti -1c
.RI "bool \fBhalted\fP"
.br
.ti -1c
.RI "float \fBlast_commanded_current\fP"
.br
.ti -1c
.RI "float \fBlast_commanded_effort\fP"
.br
.ti -1c
.RI "float \fBlast_executed_current\fP"
.br
.ti -1c
.RI "float \fBlast_executed_effort\fP"
.br
.ti -1c
.RI "float \fBlast_measured_current\fP"
.br
.ti -1c
.RI "float \fBlast_measured_effort\fP"
.br
.ti -1c
.RI "float \fBmotor_voltage\fP"
.br
.ti -1c
.RI "int32_t \fBnum_encoder_errors\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
