.TH "pr2_gazebo_plugins::SetModelsJointsStatesRequest" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pr2_gazebo_plugins::SetModelsJointsStatesRequest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBmodel_names_length\fP"
.br
.ti -1c
.RI "char * \fBst_model_names\fP"
.br
.ti -1c
.RI "char ** \fBmodel_names\fP"
.br
.ti -1c
.RI "uint8_t \fBmodel_joints_states_length\fP"
.br
.ti -1c
.RI "\fBpr2_gazebo_plugins::ModelJointsState\fP \fBst_model_joints_states\fP"
.br
.ti -1c
.RI "\fBpr2_gazebo_plugins::ModelJointsState\fP * \fBmodel_joints_states\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
