.TH "pr2_msgs::LaserTrajCmd" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pr2_msgs::LaserTrajCmd \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd_msgs::Header\fP \fBheader\fP"
.br
.ti -1c
.RI "const char * \fBprofile\fP"
.br
.ti -1c
.RI "uint8_t \fBposition_length\fP"
.br
.ti -1c
.RI "float \fBst_position\fP"
.br
.ti -1c
.RI "float * \fBposition\fP"
.br
.ti -1c
.RI "uint8_t \fBtime_from_start_length\fP"
.br
.ti -1c
.RI "\fBros::Duration\fP \fBst_time_from_start\fP"
.br
.ti -1c
.RI "\fBros::Duration\fP * \fBtime_from_start\fP"
.br
.ti -1c
.RI "float \fBmax_velocity\fP"
.br
.ti -1c
.RI "float \fBmax_acceleration\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
