.TH "pr2_mechanism_controllers::SetProfile" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pr2_mechanism_controllers::SetProfile \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBSetProfileRequest\fP \fBRequest\fP"
.br
.ti -1c
.RI "typedef \fBSetProfileResponse\fP \fBResponse\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
