.TH "pr2_msgs::DashboardState" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pr2_msgs::DashboardState \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd_msgs::Bool\fP \fBmotors_halted\fP"
.br
.ti -1c
.RI "bool \fBmotors_halted_valid\fP"
.br
.ti -1c
.RI "\fBpr2_msgs::PowerBoardState\fP \fBpower_board_state\fP"
.br
.ti -1c
.RI "bool \fBpower_board_state_valid\fP"
.br
.ti -1c
.RI "\fBpr2_msgs::PowerState\fP \fBpower_state\fP"
.br
.ti -1c
.RI "bool \fBpower_state_valid\fP"
.br
.ti -1c
.RI "\fBpr2_msgs::AccessPoint\fP \fBaccess_point\fP"
.br
.ti -1c
.RI "bool \fBaccess_point_valid\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
