.TH "pr2_gripper_sensor_msgs::PR2GripperSensorRawData" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pr2_gripper_sensor_msgs::PR2GripperSensorRawData \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBros::Time\fP \fBstamp\fP"
.br
.ti -1c
.RI "float \fBleft_finger_pad_force\fP"
.br
.ti -1c
.RI "float \fBright_finger_pad_force\fP"
.br
.ti -1c
.RI "float \fBleft_finger_pad_force_filtered\fP"
.br
.ti -1c
.RI "float \fBright_finger_pad_force_filtered\fP"
.br
.ti -1c
.RI "float \fBleft_finger_pad_forces\fP [22]"
.br
.ti -1c
.RI "float \fBright_finger_pad_forces\fP [22]"
.br
.ti -1c
.RI "float \fBleft_finger_pad_forces_filtered\fP [22]"
.br
.ti -1c
.RI "float \fBright_finger_pad_forces_filtered\fP [22]"
.br
.ti -1c
.RI "float \fBacc_x_raw\fP"
.br
.ti -1c
.RI "float \fBacc_y_raw\fP"
.br
.ti -1c
.RI "float \fBacc_z_raw\fP"
.br
.ti -1c
.RI "float \fBacc_x_filtered\fP"
.br
.ti -1c
.RI "float \fBacc_y_filtered\fP"
.br
.ti -1c
.RI "float \fBacc_z_filtered\fP"
.br
.ti -1c
.RI "bool \fBleft_contact\fP"
.br
.ti -1c
.RI "bool \fBright_contact\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
