.TH "pr2_self_test_msgs::TestInfo" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pr2_self_test_msgs::TestInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBserial\fP"
.br
.ti -1c
.RI "const char * \fBtest_name\fP"
.br
.ti -1c
.RI "int8_t \fBtest_status\fP"
.br
.ti -1c
.RI "const char * \fBbay_name\fP"
.br
.ti -1c
.RI "const char * \fBmachine\fP"
.br
.ti -1c
.RI "int32_t \fBboard\fP"
.br
.ti -1c
.RI "int32_t \fBbreaker\fP"
.br
.ti -1c
.RI "const char * \fBpower_status\fP"
.br
.ti -1c
.RI "int8_t \fBestop\fP"
.br
.ti -1c
.RI "int32_t \fBelapsed\fP"
.br
.ti -1c
.RI "const char * \fBstatus_msg\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
