.TH "pr2_msgs::GPUStatus" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pr2_msgs::GPUStatus \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd_msgs::Header\fP \fBheader\fP"
.br
.ti -1c
.RI "const char * \fBproduct_name\fP"
.br
.ti -1c
.RI "const char * \fBpci_device_id\fP"
.br
.ti -1c
.RI "const char * \fBpci_location\fP"
.br
.ti -1c
.RI "const char * \fBdisplay\fP"
.br
.ti -1c
.RI "const char * \fBdriver_version\fP"
.br
.ti -1c
.RI "float \fBtemperature\fP"
.br
.ti -1c
.RI "float \fBfan_speed\fP"
.br
.ti -1c
.RI "float \fBgpu_usage\fP"
.br
.ti -1c
.RI "float \fBmemory_usage\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
