.TH "pr2_mechanism_controllers::BaseOdometryState" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pr2_mechanism_controllers::BaseOdometryState \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBgeometry_msgs::Twist\fP \fBvelocity\fP"
.br
.ti -1c
.RI "uint8_t \fBwheel_link_names_length\fP"
.br
.ti -1c
.RI "char * \fBst_wheel_link_names\fP"
.br
.ti -1c
.RI "char ** \fBwheel_link_names\fP"
.br
.ti -1c
.RI "uint8_t \fBdrive_constraint_errors_length\fP"
.br
.ti -1c
.RI "float \fBst_drive_constraint_errors\fP"
.br
.ti -1c
.RI "float * \fBdrive_constraint_errors\fP"
.br
.ti -1c
.RI "uint8_t \fBlongitudinal_slip_constraint_errors_length\fP"
.br
.ti -1c
.RI "float \fBst_longitudinal_slip_constraint_errors\fP"
.br
.ti -1c
.RI "float * \fBlongitudinal_slip_constraint_errors\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
