.TH "pr2_msgs::BatteryState2" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pr2_msgs::BatteryState2 \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBpresent\fP"
.br
.ti -1c
.RI "bool \fBcharging\fP"
.br
.ti -1c
.RI "bool \fBdischarging\fP"
.br
.ti -1c
.RI "bool \fBpower_present\fP"
.br
.ti -1c
.RI "bool \fBpower_no_good\fP"
.br
.ti -1c
.RI "bool \fBinhibited\fP"
.br
.ti -1c
.RI "\fBros::Time\fP \fBlast_battery_update\fP"
.br
.ti -1c
.RI "int16_t \fBbattery_register\fP [48]"
.br
.ti -1c
.RI "bool \fBbattery_update_flag\fP [48]"
.br
.ti -1c
.RI "\fBros::Time\fP \fBbattery_register_update\fP [48]"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
