.TH "pr2_mechanism_msgs::SwitchController" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pr2_mechanism_msgs::SwitchController \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBSwitchControllerRequest\fP \fBRequest\fP"
.br
.ti -1c
.RI "typedef \fBSwitchControllerResponse\fP \fBResponse\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
