.TH "program_queue::Login" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
program_queue::Login \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBLoginRequest\fP \fBRequest\fP"
.br
.ti -1c
.RI "typedef \fBLoginResponse\fP \fBResponse\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
