.TH "robot_pose_ekf::GetStatus" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
robot_pose_ekf::GetStatus \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBGetStatusRequest\fP \fBRequest\fP"
.br
.ti -1c
.RI "typedef \fBGetStatusResponse\fP \fBResponse\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
