.TH "rocon_std_msgs::Strings" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rocon_std_msgs::Strings \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBROCON_VERSION\fP = acdc }"
.br
.ti -1c
.RI "enum { \fBURI_WILDCARD\fP = * }"
.br
.ti -1c
.RI "enum { \fBHW_PC\fP = pc }"
.br
.ti -1c
.RI "enum { \fBHW_TURTLEBOT2\fP = turtlebot2 }"
.br
.ti -1c
.RI "enum { \fBHW_PR2\fP = pr2 }"
.br
.ti -1c
.RI "enum { \fBHW_WAITERBOT\fP = waiterbot }"
.br
.ti -1c
.RI "enum { \fBHW_ROBOT_OTHER\fP = robot_other }"
.br
.ti -1c
.RI "enum { \fBHW_GALAXY\fP = galaxy }"
.br
.ti -1c
.RI "enum { \fBHW_MEGA\fP = mega }"
.br
.ti -1c
.RI "enum { \fBHW_NOTE3\fP = note3 }"
.br
.ti -1c
.RI "enum { \fBHW_PHONE_OTHER\fP = phone_other }"
.br
.ti -1c
.RI "enum { \fBHW_XOOM\fP = xoom }"
.br
.ti -1c
.RI "enum { \fBHW_NOTE10\fP = note10 }"
.br
.ti -1c
.RI "enum { \fBHW_TABLET_OTHER\fP = tablet_other }"
.br
.ti -1c
.RI "enum { \fBAPPLICATION_FRAMEWORK_OTHER\fP = application_framework_other }"
.br
.ti -1c
.RI "enum { \fBAPPLICATION_FRAMEWORK_OPROS\fP = opros }"
.br
.ti -1c
.RI "enum { \fBAPPLICATION_FRAMEWORK_GROOVY\fP = groovy }"
.br
.ti -1c
.RI "enum { \fBAPPLICATION_FRAMEWORK_HYDRO\fP = hydro }"
.br
.ti -1c
.RI "enum { \fBAPPLICATION_FRAMEWORK_INDIGO\fP = indigo }"
.br
.ti -1c
.RI "enum { \fBAPPLICATION_FRAMEWORK_ROS_OTHER\fP = ros_other }"
.br
.ti -1c
.RI "enum { \fBOS_OSX\fP = osx }"
.br
.ti -1c
.RI "enum { \fBOS_FREEBSD\fP = freebsd }"
.br
.ti -1c
.RI "enum { \fBOS_WINXP\fP = winxp }"
.br
.ti -1c
.RI "enum { \fBOS_WINDOWS7\fP = windows7 }"
.br
.ti -1c
.RI "enum { \fBOS_ARCH\fP = arch }"
.br
.ti -1c
.RI "enum { \fBOS_DEBIAN\fP = debian }"
.br
.ti -1c
.RI "enum { \fBOS_FEDORA\fP = fedora }"
.br
.ti -1c
.RI "enum { \fBOS_GENTOO\fP = gentoo }"
.br
.ti -1c
.RI "enum { \fBOS_PRECISE\fP = precise }"
.br
.ti -1c
.RI "enum { \fBOS_QUANTAL\fP = quantal }"
.br
.ti -1c
.RI "enum { \fBOS_RARING\fP = raring }"
.br
.ti -1c
.RI "enum { \fBOS_SAUCY\fP = saucy }"
.br
.ti -1c
.RI "enum { \fBOS_HONEYCOMB\fP = honeycomb }"
.br
.ti -1c
.RI "enum { \fBOS_ICE_CREAM_SANDWICH\fP = ice_cream_sandwich }"
.br
.ti -1c
.RI "enum { \fBOS_JELLYBEAN\fP = jellybean }"
.br
.ti -1c
.RI "enum { \fBOS_KITKAT\fP = kitkat }"
.br
.ti -1c
.RI "enum { \fBOS_CHROME\fP = chrome }"
.br
.ti -1c
.RI "enum { \fBOS_FIREFOX\fP = firefox }"
.br
.ti -1c
.RI "enum { \fBOS_INTERNET_EXPLORER\fP = internet_explorer }"
.br
.ti -1c
.RI "enum { \fBOS_SAFARI\fP = safari }"
.br
.ti -1c
.RI "enum { \fBOS_OPERA\fP = opera }"
.br
.ti -1c
.RI "enum { \fBTAG_SERVICE\fP = concert_service }"
.br
.ti -1c
.RI "enum { \fBTAG_RAPP\fP = rocon_app }"
.br
.ti -1c
.RI "enum { \fBTAG_GAZEBO_ROBOT_TYPE\fP = concert_gazebo }"
.br
.ti -1c
.RI "enum { \fBTAG_SOFTWARE\fP = software_farm }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
