.TH "rocon_app_manager_msgs::IncompatibleRappList" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rocon_app_manager_msgs::IncompatibleRappList \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBblacklisted_rapps_length\fP"
.br
.ti -1c
.RI "char * \fBst_blacklisted_rapps\fP"
.br
.ti -1c
.RI "char ** \fBblacklisted_rapps\fP"
.br
.ti -1c
.RI "uint8_t \fBnon_whitelisted_rapps_length\fP"
.br
.ti -1c
.RI "char * \fBst_non_whitelisted_rapps\fP"
.br
.ti -1c
.RI "char ** \fBnon_whitelisted_rapps\fP"
.br
.ti -1c
.RI "uint8_t \fBplatform_incompatible_rapps_length\fP"
.br
.ti -1c
.RI "char * \fBst_platform_incompatible_rapps\fP"
.br
.ti -1c
.RI "char ** \fBplatform_incompatible_rapps\fP"
.br
.ti -1c
.RI "uint8_t \fBcapabilities_incompatible_rapps_length\fP"
.br
.ti -1c
.RI "char * \fBst_capabilities_incompatible_rapps\fP"
.br
.ti -1c
.RI "char ** \fBcapabilities_incompatible_rapps\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
