.TH "rocon_interaction_msgs::GetInteraction" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rocon_interaction_msgs::GetInteraction \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBGetInteractionRequest\fP \fBRequest\fP"
.br
.ti -1c
.RI "typedef \fBGetInteractionResponse\fP \fBResponse\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
