.TH "rocon_interaction_msgs::Interaction" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rocon_interaction_msgs::Interaction \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBUNLIMITED_INTERACTIONS\fP = -1 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "const char * \fBcompatibility\fP"
.br
.ti -1c
.RI "const char * \fBdisplay_name\fP"
.br
.ti -1c
.RI "const char * \fBdescription\fP"
.br
.ti -1c
.RI "\fBrocon_std_msgs::Icon\fP \fBicon\fP"
.br
.ti -1c
.RI "uint8_t \fBremappings_length\fP"
.br
.ti -1c
.RI "\fBrocon_std_msgs::Remapping\fP \fBst_remappings\fP"
.br
.ti -1c
.RI "\fBrocon_std_msgs::Remapping\fP * \fBremappings\fP"
.br
.ti -1c
.RI "const char * \fBparameters\fP"
.br
.ti -1c
.RI "int32_t \fBmax\fP"
.br
.ti -1c
.RI "\fBrocon_interaction_msgs::Pairing\fP \fBpairing\fP"
.br
.ti -1c
.RI "int32_t \fBhash\fP"
.br
.ti -1c
.RI "const char * \fBrole\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
