.TH "rocon_app_manager_msgs::Rapp" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rocon_app_manager_msgs::Rapp \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "const char * \fBdisplay_name\fP"
.br
.ti -1c
.RI "const char * \fBdescription\fP"
.br
.ti -1c
.RI "const char * \fBcompatibility\fP"
.br
.ti -1c
.RI "const char * \fBstatus\fP"
.br
.ti -1c
.RI "uint8_t \fBimplementations_length\fP"
.br
.ti -1c
.RI "char * \fBst_implementations\fP"
.br
.ti -1c
.RI "char ** \fBimplementations\fP"
.br
.ti -1c
.RI "const char * \fBpreferred\fP"
.br
.ti -1c
.RI "\fBrocon_std_msgs::Icon\fP \fBicon\fP"
.br
.ti -1c
.RI "uint8_t \fBpublic_interface_length\fP"
.br
.ti -1c
.RI "\fBrocon_std_msgs::KeyValue\fP \fBst_public_interface\fP"
.br
.ti -1c
.RI "\fBrocon_std_msgs::KeyValue\fP * \fBpublic_interface\fP"
.br
.ti -1c
.RI "uint8_t \fBpublic_parameters_length\fP"
.br
.ti -1c
.RI "\fBrocon_std_msgs::KeyValue\fP \fBst_public_parameters\fP"
.br
.ti -1c
.RI "\fBrocon_std_msgs::KeyValue\fP * \fBpublic_parameters\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
