.TH "ros::NodeHandleBase_" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ros::NodeHandleBase_ \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBros::NodeHandle_< Hardware, MAX_SUBSCRIBERS, MAX_PUBLISHERS, INPUT_SIZE, OUTPUT_SIZE >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBpublish\fP (int id, const \fBMsg\fP *msg)=0"
.br
.ti -1c
.RI "virtual int \fBspinOnce\fP ()=0"
.br
.ti -1c
.RI "virtual bool \fBconnected\fP ()=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
