.TH "ros::Duration" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ros::Duration \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDuration\fP (int32_t _sec, int32_t _nsec)"
.br
.ti -1c
.RI "double \fBtoSec\fP () const "
.br
.ti -1c
.RI "void \fBfromSec\fP (double t)"
.br
.ti -1c
.RI "\fBDuration\fP & \fBoperator+=\fP (const \fBDuration\fP &rhs)"
.br
.ti -1c
.RI "\fBDuration\fP & \fBoperator-=\fP (const \fBDuration\fP &rhs)"
.br
.ti -1c
.RI "\fBDuration\fP & \fBoperator*=\fP (double scale)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int32_t \fBsec\fP"
.br
.ti -1c
.RI "int32_t \fBnsec\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
