.TH "ros::Subscriber_" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ros::Subscriber_ \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBros::ServiceClient< MReq, MRes >\fP, \fBros::ServiceServer< MReq, MRes >\fP, and \fBros::Subscriber< MsgT >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBcallback\fP (unsigned char *data)=0"
.br
.ti -1c
.RI "virtual int \fBgetEndpointType\fP ()=0"
.br
.ti -1c
.RI "virtual const char * \fBgetMsgType\fP ()=0"
.br
.ti -1c
.RI "virtual const char * \fBgetMsgMD5\fP ()=0"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid_\fP"
.br
.ti -1c
.RI "const char * \fBtopic_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
