.TH "roseus::VariableArray" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
roseus::VariableArray \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBfloat32_data_length\fP"
.br
.ti -1c
.RI "float \fBst_float32_data\fP"
.br
.ti -1c
.RI "float * \fBfloat32_data\fP"
.br
.ti -1c
.RI "uint8_t \fBfloat64_data_length\fP"
.br
.ti -1c
.RI "float \fBst_float64_data\fP"
.br
.ti -1c
.RI "float * \fBfloat64_data\fP"
.br
.ti -1c
.RI "uint8_t \fBint16_data_length\fP"
.br
.ti -1c
.RI "int16_t \fBst_int16_data\fP"
.br
.ti -1c
.RI "int16_t * \fBint16_data\fP"
.br
.ti -1c
.RI "uint8_t \fBint32_data_length\fP"
.br
.ti -1c
.RI "int32_t \fBst_int32_data\fP"
.br
.ti -1c
.RI "int32_t * \fBint32_data\fP"
.br
.ti -1c
.RI "uint8_t \fBint64_data_length\fP"
.br
.ti -1c
.RI "int64_t \fBst_int64_data\fP"
.br
.ti -1c
.RI "int64_t * \fBint64_data\fP"
.br
.ti -1c
.RI "uint8_t \fBint8_data_length\fP"
.br
.ti -1c
.RI "int8_t \fBst_int8_data\fP"
.br
.ti -1c
.RI "int8_t * \fBint8_data\fP"
.br
.ti -1c
.RI "uint8_t \fBuint16_data_length\fP"
.br
.ti -1c
.RI "uint16_t \fBst_uint16_data\fP"
.br
.ti -1c
.RI "uint16_t * \fBuint16_data\fP"
.br
.ti -1c
.RI "uint8_t \fBuint32_data_length\fP"
.br
.ti -1c
.RI "uint32_t \fBst_uint32_data\fP"
.br
.ti -1c
.RI "uint32_t * \fBuint32_data\fP"
.br
.ti -1c
.RI "uint8_t \fBuint64_data_length\fP"
.br
.ti -1c
.RI "uint64_t \fBst_uint64_data\fP"
.br
.ti -1c
.RI "uint64_t * \fBuint64_data\fP"
.br
.ti -1c
.RI "uint8_t \fBuint8_data_length\fP"
.br
.ti -1c
.RI "uint8_t \fBst_uint8_data\fP"
.br
.ti -1c
.RI "uint8_t * \fBuint8_data\fP"
.br
.ti -1c
.RI "uint8_t \fBbool_data_length\fP"
.br
.ti -1c
.RI "bool \fBst_bool_data\fP"
.br
.ti -1c
.RI "bool * \fBbool_data\fP"
.br
.ti -1c
.RI "uint8_t \fBtime_data_length\fP"
.br
.ti -1c
.RI "\fBros::Time\fP \fBst_time_data\fP"
.br
.ti -1c
.RI "\fBros::Time\fP * \fBtime_data\fP"
.br
.ti -1c
.RI "uint8_t \fBduration_data_length\fP"
.br
.ti -1c
.RI "\fBros::Duration\fP \fBst_duration_data\fP"
.br
.ti -1c
.RI "\fBros::Duration\fP * \fBduration_data\fP"
.br
.ti -1c
.RI "uint8_t \fBstring_data_length\fP"
.br
.ti -1c
.RI "\fBstd_msgs::String\fP \fBst_string_data\fP"
.br
.ti -1c
.RI "\fBstd_msgs::String\fP * \fBstring_data\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
