.TH "rosgraph_msgs::TopicStatistics" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rosgraph_msgs::TopicStatistics \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBtopic\fP"
.br
.ti -1c
.RI "const char * \fBnode_pub\fP"
.br
.ti -1c
.RI "const char * \fBnode_sub\fP"
.br
.ti -1c
.RI "\fBros::Time\fP \fBwindow_start\fP"
.br
.ti -1c
.RI "\fBros::Time\fP \fBwindow_stop\fP"
.br
.ti -1c
.RI "int32_t \fBdelivered_msgs\fP"
.br
.ti -1c
.RI "int32_t \fBdropped_msgs\fP"
.br
.ti -1c
.RI "int32_t \fBtraffic\fP"
.br
.ti -1c
.RI "\fBros::Duration\fP \fBperiod_mean\fP"
.br
.ti -1c
.RI "\fBros::Duration\fP \fBperiod_stddev\fP"
.br
.ti -1c
.RI "\fBros::Duration\fP \fBperiod_max\fP"
.br
.ti -1c
.RI "\fBros::Duration\fP \fBstamp_age_mean\fP"
.br
.ti -1c
.RI "\fBros::Duration\fP \fBstamp_age_stddev\fP"
.br
.ti -1c
.RI "\fBros::Duration\fP \fBstamp_age_max\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
