.TH "scheduler_msgs::SchedulerRequests" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scheduler_msgs::SchedulerRequests \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd_msgs::Header\fP \fBheader\fP"
.br
.ti -1c
.RI "\fBuuid_msgs::UniqueID\fP \fBrequester\fP"
.br
.ti -1c
.RI "uint8_t \fBrequests_length\fP"
.br
.ti -1c
.RI "\fBscheduler_msgs::Request\fP \fBst_requests\fP"
.br
.ti -1c
.RI "\fBscheduler_msgs::Request\fP * \fBrequests\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
