.TH "sensor_msgs::MultiEchoLaserScan" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sensor_msgs::MultiEchoLaserScan \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd_msgs::Header\fP \fBheader\fP"
.br
.ti -1c
.RI "float \fBangle_min\fP"
.br
.ti -1c
.RI "float \fBangle_max\fP"
.br
.ti -1c
.RI "float \fBangle_increment\fP"
.br
.ti -1c
.RI "float \fBtime_increment\fP"
.br
.ti -1c
.RI "float \fBscan_time\fP"
.br
.ti -1c
.RI "float \fBrange_min\fP"
.br
.ti -1c
.RI "float \fBrange_max\fP"
.br
.ti -1c
.RI "uint8_t \fBranges_length\fP"
.br
.ti -1c
.RI "\fBsensor_msgs::LaserEcho\fP \fBst_ranges\fP"
.br
.ti -1c
.RI "\fBsensor_msgs::LaserEcho\fP * \fBranges\fP"
.br
.ti -1c
.RI "uint8_t \fBintensities_length\fP"
.br
.ti -1c
.RI "\fBsensor_msgs::LaserEcho\fP \fBst_intensities\fP"
.br
.ti -1c
.RI "\fBsensor_msgs::LaserEcho\fP * \fBintensities\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
