.TH "sensor_msgs::CameraInfo" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sensor_msgs::CameraInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd_msgs::Header\fP \fBheader\fP"
.br
.ti -1c
.RI "uint32_t \fBheight\fP"
.br
.ti -1c
.RI "uint32_t \fBwidth\fP"
.br
.ti -1c
.RI "const char * \fBdistortion_model\fP"
.br
.ti -1c
.RI "uint8_t \fBD_length\fP"
.br
.ti -1c
.RI "float \fBst_D\fP"
.br
.ti -1c
.RI "float * \fBD\fP"
.br
.ti -1c
.RI "float \fBK\fP [9]"
.br
.ti -1c
.RI "float \fBR\fP [9]"
.br
.ti -1c
.RI "float \fBP\fP [12]"
.br
.ti -1c
.RI "uint32_t \fBbinning_x\fP"
.br
.ti -1c
.RI "uint32_t \fBbinning_y\fP"
.br
.ti -1c
.RI "\fBsensor_msgs::RegionOfInterest\fP \fBroi\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
