.TH "sensor_msgs::NavSatStatus" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sensor_msgs::NavSatStatus \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBSTATUS_NO_FIX\fP = -1 }"
.br
.ti -1c
.RI "enum { \fBSTATUS_FIX\fP = 0 }"
.br
.ti -1c
.RI "enum { \fBSTATUS_SBAS_FIX\fP = 1 }"
.br
.ti -1c
.RI "enum { \fBSTATUS_GBAS_FIX\fP = 2 }"
.br
.ti -1c
.RI "enum { \fBSERVICE_GPS\fP = 1 }"
.br
.ti -1c
.RI "enum { \fBSERVICE_GLONASS\fP = 2 }"
.br
.ti -1c
.RI "enum { \fBSERVICE_COMPASS\fP = 4 }"
.br
.ti -1c
.RI "enum { \fBSERVICE_GALILEO\fP = 8 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int8_t \fBstatus\fP"
.br
.ti -1c
.RI "uint16_t \fBservice\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
