.TH "sensor_msgs::Imu" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sensor_msgs::Imu \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd_msgs::Header\fP \fBheader\fP"
.br
.ti -1c
.RI "\fBgeometry_msgs::Quaternion\fP \fBorientation\fP"
.br
.ti -1c
.RI "float \fBorientation_covariance\fP [9]"
.br
.ti -1c
.RI "\fBgeometry_msgs::Vector3\fP \fBangular_velocity\fP"
.br
.ti -1c
.RI "float \fBangular_velocity_covariance\fP [9]"
.br
.ti -1c
.RI "\fBgeometry_msgs::Vector3\fP \fBlinear_acceleration\fP"
.br
.ti -1c
.RI "float \fBlinear_acceleration_covariance\fP [9]"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
