.TH "shape_msgs::SolidPrimitive" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shape_msgs::SolidPrimitive \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBBOX\fP = 1 }"
.br
.ti -1c
.RI "enum { \fBSPHERE\fP = 2 }"
.br
.ti -1c
.RI "enum { \fBCYLINDER\fP = 3 }"
.br
.ti -1c
.RI "enum { \fBCONE\fP = 4 }"
.br
.ti -1c
.RI "enum { \fBBOX_X\fP = 0 }"
.br
.ti -1c
.RI "enum { \fBBOX_Y\fP = 1 }"
.br
.ti -1c
.RI "enum { \fBBOX_Z\fP = 2 }"
.br
.ti -1c
.RI "enum { \fBSPHERE_RADIUS\fP = 0 }"
.br
.ti -1c
.RI "enum { \fBCYLINDER_HEIGHT\fP = 0 }"
.br
.ti -1c
.RI "enum { \fBCYLINDER_RADIUS\fP = 1 }"
.br
.ti -1c
.RI "enum { \fBCONE_HEIGHT\fP = 0 }"
.br
.ti -1c
.RI "enum { \fBCONE_RADIUS\fP = 1 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBtype\fP"
.br
.ti -1c
.RI "uint8_t \fBdimensions_length\fP"
.br
.ti -1c
.RI "float \fBst_dimensions\fP"
.br
.ti -1c
.RI "float * \fBdimensions\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
