.TH "stdr_msgs::RobotMsg" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stdr_msgs::RobotMsg \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBgeometry_msgs::Pose2D\fP \fBinitialPose\fP"
.br
.ti -1c
.RI "\fBstdr_msgs::FootprintMsg\fP \fBfootprint\fP"
.br
.ti -1c
.RI "uint8_t \fBlaserSensors_length\fP"
.br
.ti -1c
.RI "\fBstdr_msgs::LaserSensorMsg\fP \fBst_laserSensors\fP"
.br
.ti -1c
.RI "\fBstdr_msgs::LaserSensorMsg\fP * \fBlaserSensors\fP"
.br
.ti -1c
.RI "uint8_t \fBsonarSensors_length\fP"
.br
.ti -1c
.RI "\fBstdr_msgs::SonarSensorMsg\fP \fBst_sonarSensors\fP"
.br
.ti -1c
.RI "\fBstdr_msgs::SonarSensorMsg\fP * \fBsonarSensors\fP"
.br
.ti -1c
.RI "uint8_t \fBrfidSensors_length\fP"
.br
.ti -1c
.RI "\fBstdr_msgs::RfidSensorMsg\fP \fBst_rfidSensors\fP"
.br
.ti -1c
.RI "\fBstdr_msgs::RfidSensorMsg\fP * \fBrfidSensors\fP"
.br
.ti -1c
.RI "uint8_t \fBco2Sensors_length\fP"
.br
.ti -1c
.RI "\fBstdr_msgs::CO2SensorMsg\fP \fBst_co2Sensors\fP"
.br
.ti -1c
.RI "\fBstdr_msgs::CO2SensorMsg\fP * \fBco2Sensors\fP"
.br
.ti -1c
.RI "uint8_t \fBsoundSensors_length\fP"
.br
.ti -1c
.RI "\fBstdr_msgs::SoundSensorMsg\fP \fBst_soundSensors\fP"
.br
.ti -1c
.RI "\fBstdr_msgs::SoundSensorMsg\fP * \fBsoundSensors\fP"
.br
.ti -1c
.RI "uint8_t \fBthermalSensors_length\fP"
.br
.ti -1c
.RI "\fBstdr_msgs::ThermalSensorMsg\fP \fBst_thermalSensors\fP"
.br
.ti -1c
.RI "\fBstdr_msgs::ThermalSensorMsg\fP * \fBthermalSensors\fP"
.br
.ti -1c
.RI "\fBstdr_msgs::KinematicMsg\fP \fBkinematicModel\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
