.TH "stdr_msgs::SoundSensorMsg" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stdr_msgs::SoundSensorMsg \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBmaxRange\fP"
.br
.ti -1c
.RI "float \fBfrequency\fP"
.br
.ti -1c
.RI "float \fBangleSpan\fP"
.br
.ti -1c
.RI "const char * \fBframe_id\fP"
.br
.ti -1c
.RI "\fBgeometry_msgs::Pose2D\fP \fBpose\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
