.TH "ur_msgs::MasterboardDataMsg" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ur_msgs::MasterboardDataMsg \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int16_t \fBdigital_input_bits\fP"
.br
.ti -1c
.RI "int16_t \fBdigital_output_bits\fP"
.br
.ti -1c
.RI "int8_t \fBanalog_input_range0\fP"
.br
.ti -1c
.RI "int8_t \fBanalog_input_range1\fP"
.br
.ti -1c
.RI "float \fBanalog_input0\fP"
.br
.ti -1c
.RI "float \fBanalog_input1\fP"
.br
.ti -1c
.RI "int8_t \fBanalog_output_domain0\fP"
.br
.ti -1c
.RI "int8_t \fBanalog_output_domain1\fP"
.br
.ti -1c
.RI "float \fBanalog_output0\fP"
.br
.ti -1c
.RI "float \fBanalog_output1\fP"
.br
.ti -1c
.RI "float \fBmasterboard_temperature\fP"
.br
.ti -1c
.RI "float \fBrobot_voltage_48V\fP"
.br
.ti -1c
.RI "float \fBrobot_current\fP"
.br
.ti -1c
.RI "float \fBmaster_io_current\fP"
.br
.ti -1c
.RI "uint8_t \fBmaster_safety_state\fP"
.br
.ti -1c
.RI "uint8_t \fBmaster_onoff_state\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
