.TH "ur_msgs::IOStates" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ur_msgs::IOStates \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBdigital_in_states_length\fP"
.br
.ti -1c
.RI "\fBur_msgs::Digital\fP \fBst_digital_in_states\fP"
.br
.ti -1c
.RI "\fBur_msgs::Digital\fP * \fBdigital_in_states\fP"
.br
.ti -1c
.RI "uint8_t \fBdigital_out_states_length\fP"
.br
.ti -1c
.RI "\fBur_msgs::Digital\fP \fBst_digital_out_states\fP"
.br
.ti -1c
.RI "\fBur_msgs::Digital\fP * \fBdigital_out_states\fP"
.br
.ti -1c
.RI "uint8_t \fBflag_states_length\fP"
.br
.ti -1c
.RI "\fBur_msgs::Digital\fP \fBst_flag_states\fP"
.br
.ti -1c
.RI "\fBur_msgs::Digital\fP * \fBflag_states\fP"
.br
.ti -1c
.RI "uint8_t \fBanalog_in_states_length\fP"
.br
.ti -1c
.RI "\fBur_msgs::Analog\fP \fBst_analog_in_states\fP"
.br
.ti -1c
.RI "\fBur_msgs::Analog\fP * \fBanalog_in_states\fP"
.br
.ti -1c
.RI "uint8_t \fBanalog_out_states_length\fP"
.br
.ti -1c
.RI "\fBur_msgs::Analog\fP \fBst_analog_out_states\fP"
.br
.ti -1c
.RI "\fBur_msgs::Analog\fP * \fBanalog_out_states\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
