.TH "ur_msgs::RobotStateRTMsg" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ur_msgs::RobotStateRTMsg \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBtime\fP"
.br
.ti -1c
.RI "uint8_t \fBq_target_length\fP"
.br
.ti -1c
.RI "float \fBst_q_target\fP"
.br
.ti -1c
.RI "float * \fBq_target\fP"
.br
.ti -1c
.RI "uint8_t \fBqd_target_length\fP"
.br
.ti -1c
.RI "float \fBst_qd_target\fP"
.br
.ti -1c
.RI "float * \fBqd_target\fP"
.br
.ti -1c
.RI "uint8_t \fBqdd_target_length\fP"
.br
.ti -1c
.RI "float \fBst_qdd_target\fP"
.br
.ti -1c
.RI "float * \fBqdd_target\fP"
.br
.ti -1c
.RI "uint8_t \fBi_target_length\fP"
.br
.ti -1c
.RI "float \fBst_i_target\fP"
.br
.ti -1c
.RI "float * \fBi_target\fP"
.br
.ti -1c
.RI "uint8_t \fBm_target_length\fP"
.br
.ti -1c
.RI "float \fBst_m_target\fP"
.br
.ti -1c
.RI "float * \fBm_target\fP"
.br
.ti -1c
.RI "uint8_t \fBq_actual_length\fP"
.br
.ti -1c
.RI "float \fBst_q_actual\fP"
.br
.ti -1c
.RI "float * \fBq_actual\fP"
.br
.ti -1c
.RI "uint8_t \fBqd_actual_length\fP"
.br
.ti -1c
.RI "float \fBst_qd_actual\fP"
.br
.ti -1c
.RI "float * \fBqd_actual\fP"
.br
.ti -1c
.RI "uint8_t \fBi_actual_length\fP"
.br
.ti -1c
.RI "float \fBst_i_actual\fP"
.br
.ti -1c
.RI "float * \fBi_actual\fP"
.br
.ti -1c
.RI "uint8_t \fBtool_acc_values_length\fP"
.br
.ti -1c
.RI "float \fBst_tool_acc_values\fP"
.br
.ti -1c
.RI "float * \fBtool_acc_values\fP"
.br
.ti -1c
.RI "uint8_t \fBtcp_force_length\fP"
.br
.ti -1c
.RI "float \fBst_tcp_force\fP"
.br
.ti -1c
.RI "float * \fBtcp_force\fP"
.br
.ti -1c
.RI "uint8_t \fBtool_vector_length\fP"
.br
.ti -1c
.RI "float \fBst_tool_vector\fP"
.br
.ti -1c
.RI "float * \fBtool_vector\fP"
.br
.ti -1c
.RI "uint8_t \fBtcp_speed_length\fP"
.br
.ti -1c
.RI "float \fBst_tcp_speed\fP"
.br
.ti -1c
.RI "float * \fBtcp_speed\fP"
.br
.ti -1c
.RI "float \fBdigital_input_bits\fP"
.br
.ti -1c
.RI "uint8_t \fBmotor_temperatures_length\fP"
.br
.ti -1c
.RI "float \fBst_motor_temperatures\fP"
.br
.ti -1c
.RI "float * \fBmotor_temperatures\fP"
.br
.ti -1c
.RI "float \fBcontroller_timer\fP"
.br
.ti -1c
.RI "float \fBtest_value\fP"
.br
.ti -1c
.RI "float \fBrobot_mode\fP"
.br
.ti -1c
.RI "uint8_t \fBjoint_modes_length\fP"
.br
.ti -1c
.RI "float \fBst_joint_modes\fP"
.br
.ti -1c
.RI "float * \fBjoint_modes\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
