.TH "visualization_msgs::InteractiveMarker" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
visualization_msgs::InteractiveMarker \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstd_msgs::Header\fP \fBheader\fP"
.br
.ti -1c
.RI "\fBgeometry_msgs::Pose\fP \fBpose\fP"
.br
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "const char * \fBdescription\fP"
.br
.ti -1c
.RI "float \fBscale\fP"
.br
.ti -1c
.RI "uint8_t \fBmenu_entries_length\fP"
.br
.ti -1c
.RI "\fBvisualization_msgs::MenuEntry\fP \fBst_menu_entries\fP"
.br
.ti -1c
.RI "\fBvisualization_msgs::MenuEntry\fP * \fBmenu_entries\fP"
.br
.ti -1c
.RI "uint8_t \fBcontrols_length\fP"
.br
.ti -1c
.RI "\fBvisualization_msgs::InteractiveMarkerControl\fP \fBst_controls\fP"
.br
.ti -1c
.RI "\fBvisualization_msgs::InteractiveMarkerControl\fP * \fBcontrols\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
