.TH "world_canvas_msgs::GetAnnotationsRequest" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
world_canvas_msgs::GetAnnotationsRequest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBworld\fP"
.br
.ti -1c
.RI "uint8_t \fBids_length\fP"
.br
.ti -1c
.RI "\fBuuid_msgs::UniqueID\fP \fBst_ids\fP"
.br
.ti -1c
.RI "\fBuuid_msgs::UniqueID\fP * \fBids\fP"
.br
.ti -1c
.RI "uint8_t \fBnames_length\fP"
.br
.ti -1c
.RI "char * \fBst_names\fP"
.br
.ti -1c
.RI "char ** \fBnames\fP"
.br
.ti -1c
.RI "uint8_t \fBtypes_length\fP"
.br
.ti -1c
.RI "char * \fBst_types\fP"
.br
.ti -1c
.RI "char ** \fBtypes\fP"
.br
.ti -1c
.RI "uint8_t \fBkeywords_length\fP"
.br
.ti -1c
.RI "char * \fBst_keywords\fP"
.br
.ti -1c
.RI "char ** \fBkeywords\fP"
.br
.ti -1c
.RI "uint8_t \fBrelationships_length\fP"
.br
.ti -1c
.RI "\fBuuid_msgs::UniqueID\fP \fBst_relationships\fP"
.br
.ti -1c
.RI "\fBuuid_msgs::UniqueID\fP * \fBrelationships\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
