.TH "world_canvas_msgs::DeleteMap" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
world_canvas_msgs::DeleteMap \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBDeleteMapRequest\fP \fBRequest\fP"
.br
.ti -1c
.RI "typedef \fBDeleteMapResponse\fP \fBResponse\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
