.TH "yocs_msgs::WaypointListService" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
yocs_msgs::WaypointListService \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBWaypointListServiceRequest\fP \fBRequest\fP"
.br
.ti -1c
.RI "typedef \fBWaypointListServiceResponse\fP \fBResponse\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
