.TH "zeroconf_msgs::DiscoveredService" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zeroconf_msgs::DiscoveredService \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBros::Msg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBserialize\fP (unsigned char *outbuffer) const "
.br
.ti -1c
.RI "virtual int \fBdeserialize\fP (unsigned char *inbuffer)"
.br
.ti -1c
.RI "const char * \fBgetType\fP ()"
.br
.ti -1c
.RI "const char * \fBgetMD5\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "const char * \fBtype\fP"
.br
.ti -1c
.RI "const char * \fBdomain\fP"
.br
.ti -1c
.RI "const char * \fBdescription\fP"
.br
.ti -1c
.RI "const char * \fBhostname\fP"
.br
.ti -1c
.RI "uint8_t \fBipv4_addresses_length\fP"
.br
.ti -1c
.RI "char * \fBst_ipv4_addresses\fP"
.br
.ti -1c
.RI "char ** \fBipv4_addresses\fP"
.br
.ti -1c
.RI "uint8_t \fBipv6_addresses_length\fP"
.br
.ti -1c
.RI "char * \fBst_ipv6_addresses\fP"
.br
.ti -1c
.RI "char ** \fBipv6_addresses\fP"
.br
.ti -1c
.RI "int32_t \fBport\fP"
.br
.ti -1c
.RI "uint32_t \fBcookie\fP"
.br
.ti -1c
.RI "bool \fBis_local\fP"
.br
.ti -1c
.RI "bool \fBour_own\fP"
.br
.ti -1c
.RI "bool \fBwide_area\fP"
.br
.ti -1c
.RI "bool \fBmulticast\fP"
.br
.ti -1c
.RI "bool \fBcached\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
