.TH "zeroconf_msgs::AddService" 3 "Sat Jul 9 2016" "angelbot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zeroconf_msgs::AddService \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBAddServiceRequest\fP \fBRequest\fP"
.br
.ti -1c
.RI "typedef \fBAddServiceResponse\fP \fBResponse\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for angelbot from the source code\&.
